name: Utils Tests and code analysis

on: [push]

jobs:
    codacy-security-scan:
        name: Codacy Security Scan
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@main

            - name: Run Codacy Analysis CLI
              uses: codacy/codacy-analysis-cli-action@master
              with:
                    output: results.sarif
                    format: sarif
                    # Adjust severity of non-security issues
                    gh-code-scanning-compat: true
                    # Force 0 exit code to allow SARIF file generation
                    # This will handover control about PR rejection to the GitHub side
                    max-allowed-issues: 2147483647

            # Upload the SARIF file generated in the previous step
            - name: Upload SARIF results file
              uses: github/codeql-action/upload-sarif@main
              with:
                    sarif_file: results.sarif
    test:
        strategy:
            matrix:
                node: [18, 20, 22]
                os: [ubuntu-latest, macos-latest, windows-latest]
        runs-on: ${{matrix.os}}
        steps:
            - uses: actions/checkout@v4
            - name: Use node ${{ matrix.node }}
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node }}
                cache: npm
            - run: npm install
            - run: npm test