name: Utils Tests and code analysis

on: ["push"]

permissions: read-all

jobs:
    codacy-security-scan:
        permissions:
            contents: read # for actions/checkout to fetch code
            security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
        name: Codacy Security Scan
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@main

            - name: Run Codacy Analysis CLI
              uses: codacy/codacy-analysis-cli-action@master

    test:
        strategy:
            matrix:
                node: [18, 20, 22]
                os: [ubuntu-latest, macos-latest, windows-latest]
        runs-on: ${{matrix.os}}
        steps:
            - uses: actions/checkout@main
            - name: Use node ${{ matrix.node }}
              uses: actions/setup-node@main
              with:
                  node-version: ${{ matrix.node }}
                  cache: npm
            - run: npm install
            - run: npm test
